# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "People"
  url = "#people"
  weight = 10
  
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20
  
[[main]]
  name = "Schedule"
  url = "#experience"
  weight = 30
  
[[main]]
  name = "Location"
  url = "#contact"
  weight = 40

 [[main]]
    name = "Syllabus"
    url = "files/csu_msmb_syllabus.pdf"
    weight = 50
